apiVersion: v1
kind: Service
metadata:
   namespace: ORGNIZATION
   name: PEER_NAME
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: PEER_NAME
   org: ORGNIZATION
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: PEER_PORT
     targetPort: PEER_PORT
     nodePort: NODEPORT_PEER

   - name: chaincode-listen
     protocol: TCP
     port: PEER_CHAINCODE_PORT
     targetPort: PEER_CHAINCODE_PORT
     nodePort: NODEPORT_CHAINCODE

   - name: peer-event-listen
     protocol: TCP
     port: PEER_EVENT_PORT
     targetPort: PEER_EVENT_PORT
     nodePort: NODEPORT_EVENT
---
