apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ORGNIZATION
  name:	PEER_NAME-ORGNIZATION
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: peer
       peer-id: PEER_NAME
       org: ORGNIZATION
    spec:

      containers:
      - name: couchdb
        image: hyperledger/fabric-couchdb
        ports:
         - containerPort: COUDH_DB_PORT


      - name: PEER_NAME-ORGNIZATION
        image: hyperledger/fabric-peer
        env:
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:COUDH_DB_PORT"
        - name: CORE_VM_ENDPOINT
          value: "unix:///host/var/run/docker.sock"
        - name: CORE_LOGGING_LEVEL
          value: "DEBUG"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false" 
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/etc/hyperledger/crypto/peer/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/etc/hyperledger/crypto/peer/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/etc/hyperledger/crypto/peer/tls/ca.crt"
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/crypto/peer/msp
        - name: CORE_PEER_ID
          value: PEER_NAME.ORGNIZATION
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: PEER_NAME.ORGNIZATION:PEER_PORT
        - name: CORE_PEER_LOCALMSPID
          value: ORGNIZATIONMSP
        - name: CORE_PEER_ADDRESS
          value: PEER_NAME.ORGNIZATION:7051
        - name: CORE_PEER_CHAINCODEADDRESS
          value: PEER_NAME.ORGNIZATION:7052
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
         - containerPort: PEER_PORT
         - containerPort: PEER_CHAINCODE_PORT
         - containerPort: PEER_EVENT_PORT
        command: ["/bin/sh"]
        args: ["-c","peer node start;"]
        volumeMounts:
         - mountPath: /etc/hyperledger/crypto/peer
           name: artifacts
           subPath:  DOMAIN/crypto-config/peerOrganizations/ORGNIZATION/peers/PEER_NAME.ORGNIZATION
         - mountPath: /opt/gopath/src/org/peer/channel-artifacts
           name: artifacts
           subPath:  DOMAIN/channel
         - mountPath: /host/var/run/
           name: run
         - mountPath: /etc/hyperledger/crypto/orderer
           name: artifacts
           subPath:  DOMAIN/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN

      - name: cli
        image:  hyperledger/fabric-tools
        env:
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_LOCALMSPTYPE
          value: "bccsp"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_LOCALMSPID
          value: ORGNIZATIONMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/crypto/peer/users/Admin@ORGNIZATION/msp
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/crypto/peer/peers/PEER_NAME.ORGNIZATION/tls/server.key
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/crypto/peer/peers/PEER_NAME.ORGNIZATION/tls/server.crt
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/crypto/peer/peers/PEER_NAME.ORGNIZATION/tls/ca.crt
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_ADDRESS
          value: PEER_NAME.ORGNIZATION:PEER_PORT
        workingDir: /opt/gopath/src/org/peer/channel-artifacts
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - mountPath: /host/var/run/
            name: run

          - mountPath: /etc/hyperledger/crypto/peer
            name: artifacts
            subPath: DOMAIN/crypto-config/peerOrganizations/ORGNIZATION
          - mountPath: /opt/gopath/src/org/peer/channel-artifacts
            name: artifacts
            subPath: DOMAIN/channel

          - mountPath: /etc/hyperledger/crypto/orderer
            name: artifacts
            subPath: DOMAIN/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN
          - mountPath: /opt/chaincode
            name: artifacts
            subPath: DOMAIN/chaincode/java

          - mountPath: /opt/gopath/src
            name: artifacts
            subPath: DOMAIN/chaincode/go



      volumes:
         - name: artifacts
           persistentVolumeClaim:
             claimName: ORGNIZATION-pv
         - name: run
           hostPath:
             path: /var/run
             type: Directory
       

---
apiVersion: v1
kind: Service
metadata:
   namespace: ORGNIZATION
   name: PEER_NAME
spec:
 selector:
   app: hyperledger
   role: peer
   peer-id: PEER_NAME
   org: ORGNIZATION
 type: NodePort
 ports:
   - name: externale-listen-endpoint
     protocol: TCP
     port: PEER_PORT
     targetPort: PEER_PORT
     nodePort: NODEPORT_PEER

   - name: chaincode-listen
     protocol: TCP
     port: PEER_CHAINCODE_PORT
     targetPort: PEER_CHAINCODE_PORT
     nodePort: NODEPORT_CHAINCODE

   - name: peer-event-listen
     protocol: TCP
     port: PEER_EVENT_PORT
     targetPort: PEER_EVENT_PORT
     nodePort: NODEPORT_EVENT
---
