apiVersion: v1
kind: Namespace
metadata:
    name: ORGNIZATION

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ORGNIZATION-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/"
    server: NFS_IP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: ORGNIZATION
 name: ORGNIZATION-pv
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: ""
 resources:
   requests:
     storage: 10Mi

---
