###channel-artifacts is no room to place, however bind it to the orderer is an good idea

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: DOMAIN
  name: ORDERER_NAME-DOMAIN
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        domain: DOMAIN
        orderer-id: ORDERER_NAME
    spec:
      containers:
      - name: ORDERER_NAME
        image: hyperledger/fabric-orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /etc/hyperledger/configtx/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /etc/hyperledger/crypto/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /etc/hyperledger/crypto/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /etc/hyperledger/crypto/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/etc/hyperledger/crypto/orderer/tls/ca.crt]'
        workingDir: /etc/hyperledger
        ports:
         - containerPort: ORDERER_PORT
        command: ["orderer"]
        volumeMounts:
         - mountPath: /etc/hyperledger/crypto/orderer
           name: artifacts
           subPath: DOMAIN/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/
         - mountPath: /etc/hyperledger/configtx
           name: artifacts
           subPath: DOMAIN/channel

      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: DOMAIN-pv


---
apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: DOMAIN
spec:
 selector:
   app: hyperledger
   role: orderer
   domain: DOMAIN
   orderer-id: ORDERER_NAME
 type: NodePort
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: ORDERER_PORT
     targetPort: ORDERER_PORT
     nodePort: NODEPORT
