
    - &ORG
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ORGMSP

        # ID to load the MSP definition as
        ID: ORGMSP

        MSPDir: crypto-config/peerOrganizations/ORG/msp
        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ORGMSP.admin', 'ORGMSP.peer','ORGMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ORGMSP.admin', 'ORGMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ORGMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.ORG
              Port: 7051
