#apiVersion: v1
#kind: PersistentVolume
#metadata:
#    name: $artifactsName
#spec:
#    capacity:
#       storage: 500Mi
#    accessModes:
#       - ReadWriteMany
#    nfs:
#      path: /opt/share/channel-artifacts
#      server: 10.112.122.9 #change to your nfs server ip here
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#    namespace: $namespace
#    name: $artifactsName
#spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#      requests:
#        storage: 10Mi
#
#---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   namespace: DOMAIN
   name: cli.ORG.DOMAIN
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: cli.ORG.DOMAIN
          image:  hyperledger/fabric-tools:x86_64-1.1.0
          env:
          
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          #- name: CORE_PEER_TLS_CERT_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.crt
          #- name: CORE_PEER_TLS_KEY_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/server.key
          #- name: CORE_PEER_TLS_ROOTCERT_FILE
          #  value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1/peers/peer0.org1/tls/ca.crt
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_LOGGING_LEVEL
            value: DEBUG
          - name: CORE_PEER_ID
            value: PEER_NAME
          - name: CORE_PEER_ADDRESS
            value: PEER_NAME.ORG.DOMAIN
          - name: CORE_PEER_LOCALMSPID
            value: ORGMSP
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/crypto/peer/msp
          workingDir: /etc/hyperledger/artifacts
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
          # - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer
          #   name: certificate
          #   subPath: scripts
           - mountPath: /host/var/run/
             name: run
          # - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
          #   name: certificate
          #   subPath: chaincode
           - mountPath: /etc/hyperledger/crypto/peer
             name: certificate
             subPath: $mspPath
           - mountPath: /etc/hyperledger/artifacts
             name: artifacts
      volumes:
        - name: artifacts
          persistentVolumeClaim:
              claimName: $artifactsName
        - name: run
          hostPath:
            path: /var/run
         - name: certificate
                 hostPath:
                   path: hf/crypto-config/peerOrganizations/ORG.DOMAIN/users/Admin@ORG.DOMAIN
                   type: Directory
         - name: run
                 hostPath:
                   path: /var/run
                   type: Directory
        - name: artifacts
                 hostPath:
                   path: hf/
                   type: Directory


