###channel-artifacts is no room to place, however bind it to the orderer is an good idea

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: DOMAIN
  name: ORDERER_NAME-DOMAIN
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        domain: DOMAIN
        orderer-id: ORDERER_NAME
    spec:
      initContainers:
      - name: init-myservice
        image: "gcr.io/GCP_PROJECT_NAME/gcsfuse"
        imagePullPolicy: Always
        command: ['sh', '-c', 'bash /gcsfuse/setUp.sh']
        securityContext:
           privileged: true
           capabilities:
             add:
               - SYS_ADMIN
        env:
          - name: DESTINATION_DIR
            value: "/hf"
          - name: FUSE_MOUNT_DIR
            value: "/gcsfuse/temp"
          - name: FUSE_BUCKET_NAME
            value: "GCS_BUCKET"
          - name: CRYPTO
            value: "DOMAIN/crypto-config/ordererOrganizations/DOMAIN"
          - name: CHANNEL
            value: "DOMAIN/channel"
        volumeMounts:
         - name: certificate
           mountPath: /hf/DOMAIN/crypto-config/ordererOrganizations/DOMAIN/orderers/orderer.DOMAIN/
         - name: channel
           mountPath: /hf/DOMAIN/channel

      containers:
      - name: ORDERER_NAME
        image: hyperledger/fabric-orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /etc/hyperledger/configtx/genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /etc/hyperledger/crypto/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /etc/hyperledger/crypto/orderer/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /etc/hyperledger/crypto/orderer/tls/server.crt
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: '[/etc/hyperledger/crypto/orderer/tls/ca.crt]'
        workingDir: /etc/hyperledger
        ports:
         - containerPort: ORDERER_PORT
        command: ["orderer"]
        volumeMounts:
         - mountPath: /etc/hyperledger/crypto/orderer
           name: certificate
         - mountPath: /etc/hyperledger/configtx
           name: channel
      volumes:
           - name: certificate
             emptyDir: {}
           - name: channel
             emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: DOMAIN
spec:
 selector:
   app: hyperledger
   role: orderer
   domain: DOMAIN
   orderer-id: ORDERER_NAME
 type: NodePort
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: ORDERER_PORT
     targetPort: ORDERER_PORT
     nodePort: NODEPORT
