#!/usr/bin/env bash

mkdir -p $FUSE_MOUNT_DIR
mkdir -p $DESTINATION_DIR/$CHANNEL
mkdir -p $DESTINATION_DIR/$CRYPTO
mkdir -p $DESTINATION_DIR/$CHAINCODE
mkdir -p $DESTINATION_DIR/$ORDERER_TLS

gcsfuse -o allow_other --implicit-dirs $FUSE_BUCKET_NAME $FUSE_MOUNT_DIR
echo "Mounted succesfully FUSE bucket $FUSE_BUCKET_NAME in $FUSE_MOUNT_DIR"
ls $FUSE_MOUNT_DIR
cp -av  $FUSE_MOUNT_DIR/$CHANNEL/* $DESTINATION_DIR/$CHANNEL/
cp -av  $FUSE_MOUNT_DIR/$CRYPTO/peers/$PEER_NAME.$ORG/* $DESTINATION_DIR/$CRYPTO/peers/$PEER_NAME.$ORG/
cp -av  $FUSE_MOUNT_DIR/$CRYPTO/users/Admin@$ORG/* $DESTINATION_DIR/$CRYPTO/users/Admin@$ORG/
cp -av  $FUSE_MOUNT_DIR/$CHAINCODE/* $DESTINATION_DIR/$CHAINCODE/
cp -av  $FUSE_MOUNT_DIR/$ORDERER_TLS/* $DESTINATION_DIR/$ORDERER_TLS/
ls $DESTINATION_DIR/$CHANNEL
ls $DESTINATION_DIR/$CRYPTO
ls $DESTINATION_DIR/$CHAINCODE
ls $DESTINATION_DIR/$ORDERER_TLS
