#!/usr/bin/env bash


mkdir -p $FUSE_MOUNT_DIR
mkdir -p $DESTINATION_DIR/$CHANNEL

if [ ! -z "$PEER_CATEGORY" ]; then
  mkdir -p $DESTINATION_DIR/$CRYPTO/peers/$PEER.$PEER_CATEGORY
  mkdir -p $DESTINATION_DIR/$CRYPTO/users/$USER_NAME@$PEER_CATEGORY
  mkdir -p $DESTINATION_DIR/$ORDERER_TLS
  mkdir -p $DESTINATION_DIR/$CHAINCODE

else
 mkdir -p $DESTINATION_DIR/$CRYPTO
fi
gcsfuse -o allow_other --implicit-dirs $FUSE_BUCKET_NAME $FUSE_MOUNT_DIR
echo "Mounted succesfully FUSE bucket $FUSE_BUCKET_NAME in $FUSE_MOUNT_DIR"
ls $FUSE_MOUNT_DIR
cp -av  $FUSE_MOUNT_DIR/$CHANNEL/* $DESTINATION_DIR/$CHANNEL/

if [ ! -z "$PEER_CATEGORY" ]; then
  cp -av  $FUSE_MOUNT_DIR/$CRYPTO/peers/$PEER.$PEER_CATEGORY/* $DESTINATION_DIR/$CRYPTO/peers/$PEER.$PEER_CATEGORY/
  cp -av  $FUSE_MOUNT_DIR/$CRYPTO/users/$USER_NAME@$PEER_CATEGORY/* $DESTINATION_DIR/$CRYPTO/users/$USER_NAME@$PEER_CATEGORY/
  cp -av  $FUSE_MOUNT_DIR/$ORDERER_TLS/* $DESTINATION_DIR/$ORDERER_TLS/
  cp -av  $FUSE_MOUNT_DIR/$CHAINCODE/* $DESTINATION_DIR/$CHAINCODE/
else
  cp -av  $FUSE_MOUNT_DIR/$CRYPTO/* $DESTINATION_DIR/$CRYPTO/
fi


ls $DESTINATION_DIR/$CHANNEL
ls $DESTINATION_DIR/$CRYPTO
ls $DESTINATION_DIR/$CHAINCODE
ls $DESTINATION_DIR/$ORDERER_TLS
